import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: 'Next.js',
    template: '%s | Next.js',
    absolute: '',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '20px', textAlign: 'center' }}>
          Header
        </header>
        <main style={{ padding: '20px', textAlign: 'center' }}>
          {children}
        </main>
        <footer style={{ backgroundColor: 'grey',  padding: '20px', textAlign: 'center'  }}>
          Footer
        </footer>
      </body>
    </html>
  )
}
