import { Metadata } from "next"
import './global.css';
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    default: 'Next.js',
    template: '%s | Next.js',
    absolute: '',
  },
  description: 'Generated by Next.js',
}

const navLinks = [
  { name: 'Register', href: '/register' },
  { name: 'Login', href: '/login' },
  { name: 'Logout', href: '/logout' },
]
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav style={{ backgroundColor: 'lightgreen', padding: '20px', textAlign: 'center' }}>
          {navLinks.map((link) => (
            <Link key={link.href} href={link.href} className="mx-2 font-bold ">{link.name}</Link>
          ))}
        </nav>
        <header style={{ backgroundColor: 'lightblue', padding: '20px', textAlign: 'center' }}>
          Header
        </header>
        <main style={{ padding: '20px', textAlign: 'center' }}>
          {children}
        </main>
        <footer style={{ backgroundColor: 'grey',  padding: '20px', textAlign: 'center'  }}>
          Footer
        </footer>
      </body>
    </html>
  )
}
