import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by Next.js',
}
function docs() {
  return (
    <div>Welcome to Docs home page</div>
  )
}

export default docs